name: Deploy to Bakery

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BAKERY_SSH_KEY }}
          SSH_HOST: satsuma.jevido.wtf
          APP_DOMAIN: kribby.jevido.wtf
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          rsync -e "ssh -i key.pem -o StrictHostKeyChecking=no" -az ./ root@$SSH_HOST:/srv/bakery/apps/$APP_DOMAIN
          ssh -i key.pem -o StrictHostKeyChecking=no root@$SSH_HOST "bakery deploy $APP_DOMAIN"
