name: Deploy to Bakery

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
          ssh-private-key: ${{ secrets.BAKERY_SSH_KEY }}
          ssh-user: root
          ssh-host: jevido.wtf
          app-domain: kribby.jevido.wtf

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Bakery
        
        run: |
          echo "$ssh-private-key" > key.pem
          chmod 600 key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $ssh-host >> ~/.ssh/known_hosts
          rsync -e "ssh -i key.pem" -az ./ $ssh-user@$ssh-host:/srv/bakery/apps/$app-domain
          ssh -i key.pem $ssh-user@$ssh-host "bakery deploy $app-domain"
      