name: Deploy to Bakery

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.BAKERY_SSH_KEY }}
      SSH_USER: root
      SSH_HOST: jevido.wtf
      APP_DOMAIN: kribby.jevido.wtf

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Bakery
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          cat key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          rsync -e "ssh -i key.pem" -az ./ $SSH_USER@$SSH_HOST:/srv/bakery/apps/$APP_DOMAIN
          ssh -i key.pem $SSH_USER@$SSH_HOST "bakery deploy $APP_DOMAIN"
